### ISSUE TITLE
TravisCI times out

### ISSUE THREAD

**Issue by neozenith** [dbader/pytest-mypy#46]
In the course of adding py3.8 support in PR #44 the author also added `mypy==0.720` which tipped the testing matrix for `py36` over the 50 minute time limit.

This issue proposes changing the `.travis.yml` to partition the testing matrix.

How that should happen... is open discussion. 

Over at `vcrpy` they use the following:
```yml
env:
    matrix:
        - TOX_SUFFIX="flakes"
        - TOX_SUFFIX="requests"
        - TOX_SUFFIX="httplib2"
        - TOX_SUFFIX="boto3"
        - TOX_SUFFIX="urllib3"
        - TOX_SUFFIX="tornado4"
        - TOX_SUFFIX="aiohttp"
script:
- tox -e "${TOX_SUFFIX}"
```
https://github.com/kevin1024/vcrpy/blob/master/.travis.yml

So we could partition by pytest versions or mypy versions.

There will have to be some careful interplay between the `.travis.yml` and `tox.ini`
